version: '3.8'

services:
  php:
    build: .
    container_name: "php"
    image: php:8.1.16-apache
    volumes:
      - ./:/var/www/html/
    ports:
      - "83:80"

  db:
    image: mariadb:10.5
    container_name: "db"
    restart: always
    volumes: 
      - ./db/banco.sql:/docker-entrypoint-initdb.d/banco.sql
      - ./db/inserts.sql:/docker-entrypoint-initdb.d/inserts.sql
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=123
    ports:
      - "3307:3306"
  composer:
    image: composer:latest
    container_name: "composer"
    volumes:
      - .:/app
    working_dir: /app
    command: install
  phpunit:
    image: php:8.1.16-cli
    container_name: "phpunit"
    volumes:
      - .:/app
    working_dir: /app
    command: vendor/bin/phpunit
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123

