services:
  - type: web
    name: gym-genesis-staging
    runtime: docker
    branch: stack-30-monitoramento-producao
    plan: free
    autoDeployTrigger: checksPass
    healthCheckPath: /ready
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: /bin/sh scripts/start-render.sh
    envVars:
      - key: APP_ENV
        value: staging
      - key: APP_DEBUG
        value: "false"
      - key: PORT
        value: "10000"
      - key: APP_SECRET
        generateValue: true
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL_CA
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: Gym Genesis Staging
