ALTER TABLE resposta_forum DROP FOREIGN KEY fk_resposta_forum_academia, DROP COLUMN academia_id;
ALTER TABLE perfil_usuario DROP FOREIGN KEY fk_perfil_usuario_academia, DROP COLUMN academia_id;
ALTER TABLE perfil_professor DROP FOREIGN KEY fk_perfil_professor_academia, DROP COLUMN academia_id;
ALTER TABLE meta_usuario DROP FOREIGN KEY fk_meta_academia, DROP COLUMN academia_id;
ALTER TABLE cupom_desconto DROP FOREIGN KEY fk_cupom_academia, DROP COLUMN academia_id;
ALTER TABLE produto DROP FOREIGN KEY fk_produto_academia, DROP COLUMN academia_id;
ALTER TABLE pedido DROP FOREIGN KEY fk_pedido_academia, DROP COLUMN academia_id;
ALTER TABLE historico_treino DROP FOREIGN KEY fk_historico_treino_academia, DROP COLUMN academia_id;
ALTER TABLE historico_peso DROP FOREIGN KEY fk_historico_peso_academia, DROP COLUMN academia_id;
ALTER TABLE forum DROP FOREIGN KEY fk_forum_academia, DROP COLUMN academia_id;
ALTER TABLE endereco DROP FOREIGN KEY fk_endereco_academia, DROP COLUMN academia_id;
ALTER TABLE dieta DROP FOREIGN KEY fk_dieta_academia, DROP COLUMN academia_id;
ALTER TABLE avaliacao_fisica DROP FOREIGN KEY fk_avaliacao_academia, DROP COLUMN academia_id;
ALTER TABLE aula_agendada DROP FOREIGN KEY fk_aula_agendada_academia, DROP COLUMN academia_id;
ALTER TABLE treino DROP FOREIGN KEY fk_treino_academia, DROP COLUMN academia_id;
ALTER TABLE funcionario DROP FOREIGN KEY fk_funcionario_academia, DROP COLUMN academia_id;
ALTER TABLE assinatura DROP FOREIGN KEY fk_assinatura_academia, DROP COLUMN academia_id;
ALTER TABLE plano DROP FOREIGN KEY fk_plano_academia, DROP COLUMN academia_id;
DROP TABLE academia_usuario;
DROP TABLE unidades;
DROP TABLE academias;