CREATE TABLE IF NOT EXISTS aluno (
  idaluno INT NOT NULL AUTO_INCREMENT,
  academia_id BIGINT UNSIGNED NOT NULL,
  unidade_id BIGINT UNSIGNED NULL,
  usuario_id INT NOT NULL,
  matricula VARCHAR(40) NOT NULL,
  nome VARCHAR(120) NOT NULL,
  cpf VARCHAR(14) NULL,
  rg VARCHAR(20) NULL,
  data_nascimento DATE NULL,
  sexo VARCHAR(20) NULL,
  telefone VARCHAR(25) NULL,
  telefone_emergencia VARCHAR(25) NULL,
  contato_emergencia VARCHAR(120) NULL,
  objetivo VARCHAR(255) NULL,
  observacoes TEXT NULL,
  status ENUM('ativo','inativo','suspenso') NOT NULL DEFAULT 'ativo',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (idaluno),
  UNIQUE KEY uq_aluno_academia_usuario (academia_id, usuario_id),
  UNIQUE KEY uq_aluno_academia_matricula (academia_id, matricula),
  KEY idx_aluno_academia_status (academia_id, status),
  KEY idx_aluno_unidade (unidade_id),
  CONSTRAINT fk_aluno_academia FOREIGN KEY (academia_id) REFERENCES academias(idacademia),
  CONSTRAINT fk_aluno_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(idunidade),
  CONSTRAINT fk_aluno_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(idusuario)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;