version: "3"
services:
  node:
    build: .
    container_name: "node_app"
    ports:
      - "3000:3000"
    volumes:
      - ./codigo:/app/codigo
    environment:
      - NODE_ENV=development

  db:
    image: mariadb:10.5
    container_name: "mariadb-server"
    restart: always
    volumes:
      - ./documentacao/banco.sql:/docker-entrypoint-initdb.d/banco.sql
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=123
    ports:
      - "3307:3306"
